package pers.jun.dao;

import org.apache.ibatis.annotations.Mapper;
import pers.jun.pojo.Item;
import pers.jun.service.model.ItemModel;

import java.util.List;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Item record);

    /**
     * 增加销量
     */
    int increaseSales(int id,int amount);

    /**
     * 根据分类id查找
     */
    List<Item> selectByCategory(int categoryId);

    /**
     * 查询所有
     */
    List<Item> selectList();

    /**
     * 查询热门商品
     */
    List<Item> getPopular(int count);

    /**
     * 模糊查找
     */
    List<Item> getListByName(String key);
}